#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# sudo not required for some system commands.
for x in mount unmount sv pacman updatedb su reboot; do
	alias $x="doas $x"
done

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -viI" \
	bc="bc -ql" \
	mkd="mkdir -pv" \
	ffmpeg="ffmpeg -hide_banner"

alias \
	ls="ls -ahlN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto"

# My aliases for different programs
alias \
	lg="lazygit" \
	gpuwatch="watch -n1 nvidia-smi" \
	zsource="source $HOME/.config/zsh/.zshrc" \
	sdn="sudo shutdown -h now" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="sudo pacman" \
  dots="/usr/bin/git --git-dir=$HOME/dotfiles/ --work-tree=$HOME" \
  npm="fnm" \
  z="zathura" \
  mbsync="mbsync -c $MBSYNCRC" \
  monerod="monerod --data-dir "$XDG_DATA_HOME"/bitmonero" \
  wget="wget --hsts-file=$XDG_DATA_HOME/wget-hsts" \
  hss="hugo server --noHTTPCache" \
  tmux="tmux -u"

# Pushing to multiple git repositories
alias gua="git remote | xargs -L1 git push --all"
alias dua="dots remote | xargs -L1 git --git-dir=$HOME/dotfiles/ --work-tree=$HOME push --all"

# Doas smooth transition
alias sudo="doas"

# Haskell formatter
alias fourmolu="$HOME/.local/share/cabal/bin/fourmolu"
