#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

setbg &			            # Set the background with the `setbg` script
xset r rate 300 50 &	  # Speed xrate up
unclutter &		          # Remove mouse when idle
xbanish &		            # Remove mouse when typing
dwmblocks &             # Status bar
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!

autostart="xcompmgr dunst unclutter pipewire pipewire-pulse pipewire-media-session"

for program in $autostart; do
	pidof -s "$program" || setsid -f "$program"
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
