#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

setbg &			        # Set the background with the `setbg` script
# xcompmgr &		        # xcompmgr for transparency
xset r rate 300 50 &	# Speed xrate up
unclutter &		        # Remove mouse when idle
xbanish &		        # Remove mouse when typing
dwmblocks &             # Status bar
xrdb xresources &
echo $PATH > /tmp/path.dbg

# This line autostart an instance of Pulseaudio that does not exit on idle.
# This is "necessary" on Artix due to a current bug between PA and 
# Chromium-based browsers where they fail to start PA and use dummy output.
pidof -s runit &&
	! pidof -s pulseaudio >/dev/null 2>&11 &&
	setid -f pulseaudio --start --exit-idle-time=-1 >/dev/null 2>&1
