require('plugins')
require('globals')
require('_utils')
vim.cmd('luafile ~/.config/nvim/language-settings.lua')
require('_autocommands')
require('settings')
require('mappings')
require('colorscheme')
require('_galaxyline')
require('_comment')
require('_compe')
require('_barbar')
require('_dashboard')
require('_telescope')
require('_gitsigns')
require('_nvimtree')
require('_treesitter')
require('_autopairs')
require('_rnvimr')
require('_vim-rooter')
require('_quickscope')
require('_neogit')
require('_which-key')
require('_true-zen')

vim.cmd('source ~/.config/nvim/vim-script/functions.vim')

-- LSP
require('lsp')
require('lsp.clangd')
require('lsp.lua-ls')
require('lsp.bash-ls')
require('lsp.python-ls')
require('lsp.rust-ls')
require('lsp.json-ls')
require('lsp.yaml-ls')
require('lsp.vim-ls')
require('lsp.docker-ls')
require('lsp.emmet-ls')
require('lsp.efm-general-ls')
