-- General mappings
require('plugins')
require('mappings')
require('settings')
require('colorscheme')
require('_utils')

-- Plugins
require('_compe')
require('_telescope')
require('_autopairs')
require('_closetag')
require('_colorizer')
require('_comment')
require('_floaterm')
require('_gitblame')
require('_gitsigns')
require('_hop')
require('_illuminate')
require('_matchup')
-- require('_limeligth')
require('_neogit')
require('_nvimtree')
require('_quickscope')
require('_rnvimr')
require('_startify')
-- require('_treesitter')
require('_vim-rooter')
require('_vim-bbye')

-- bufferline and statusline
require('_galaxyline')
require('_bufferline')

-- Load vim scripts
-- Which Key (Hope to replace with Lua plugin someday)
vim.cmd('source ~/.config/nvim/vim-script/_goyo/init.vim')
vim.cmd('source ~/.config/nvim/vim-script/_limelight/init.vim')
vim.cmd('source ~/.config/nvim/vim-script/_whichkey/init.vim')

-- LSP
require('_lspkind')
require('_lsp')
require('_lsp.bash-ls')
require('_lsp.docker-ls')
require('_lsp.lua-ls')
require('_lsp.json-ls')
require('_lsp.vim-ls')
require('_lsp.python-ls')
require('_lsp.yaml-ls')
